version: '3'

services:
    db:
        container_name: 'user-api_db'
        image: mysql:5.7
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: '!Er83lDf5BmsQ8fgcK!'
            MYSQL_DATABASE: 'user_api'
            MYSQL_USER: 'user_api_user'
            MYSQL_PASSWORD: '!Df5Bmsr83l8KQfgcE!'
        ports:
            - 3366:3306
        volumes:
            - "db_app:/var/lib/mysql"
        networks:
            - symfony
    php:
        container_name: 'user-api_php'
        build:
            context: ./docker
            dockerfile: Dockerfile-php
        depends_on:
            - db
        volumes:
            - ./:/var/www/html/
        networks:
            - symfony
    nginx:
        container_name: 'user-api_nginx'
        build:
            context: ./docker
            dockerfile: Dockerfile-nginx
        depends_on:
            - php
        volumes:
            - ./:/var/www/html/
        ports:
            - 8081:80
        networks:
            - symfony

volumes:
    db_app:

networks:
    symfony:
