FROM php:7.4-fpm

RUN apt-get update

RUN apt-get install libpng-dev curl git nano vim zip unzip -y

RUN docker-php-ext-install pdo pdo_mysql gd mysqli

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
